# ----------------------------------------------
mybatis:
  # mappers 的路径
  mapper-locations: classpath:mappers/*.xml
  # PO 的包路径，不用在xml文件写实体类的全路径（逗号隔开可配多个）
  type-aliases-package: com.test.po
  # 类型转化器的包路径，继承 org.apache.ibatis.type.BaseTypeHandler（逗号隔开可配多个）
  type-handlers-package: com.test.dao.handlers
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true

# ----------------------------------------------
spring:
  shardingsphere:
    datasource:
      names: ds0-master, ds1-master, ds0-slave, ds1-slave
      ds0-master:
        driver-class-name: com.mysql.jdbc.Driver,
        jdbcUrl: jdbc:mysql://localhost:3306/test0?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource
      ds1-master:
        driver-class-name: com.mysql.jdbc.Driver,
        jdbcUrl: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource
      ds0-slave:
        driver-class-name: com.mysql.jdbc.Driver,
        jdbcUrl: jdbc:mysql://localhost:3307/test0?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource
      ds1-slave:
        driver-class-name: com.mysql.jdbc.Driver,
        jdbcUrl: jdbc:mysql://localhost:3307/test1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource
    sharding:
      master-slave-rules:
        ds0:
          master-data-source-name: ds0-master
          slave-data-source-names: ds0-slave
        ds1:
          master-data-source-name: ds1-master
          slave-data-source-names: ds1-slave
      tables:
        user:
          actual-data-nodes: ds$->{0..1}.user_$->{0..1}
          database-strategy.inline:
            algorithm-expression: ds$->{id % 2}
            sharding-column: id
          table-strategy.inline:
            algorithm-expression: user_$->{id.intdiv(2) % 2}
            sharding-column: id
    props.sql.show: true


